### ISSUE TITLE
Remember Me

### ISSUE THREAD

**Issue by jazzyjackson** [eraeco/pay#10]
- an opt-in feature for checkard will keep, in encrypted\* local storage, your name, bank name & address, acct/routing #s,
	- and be able to intelligently fill out the check
		- when creating a new check to send:
			- the check is 'from' me, so put my bank's address in the upper left of the corner, plus acct/routing #, maybe increment the check number from last-known-check
		- when create a paylink, besides applying the amount(s) to the url, you can automatically specify recipient-bank, payee,
			- when paylink is opened, if they have filled out a check before, it will fill out the rest, just like when creating a new check
	- \* maybe you stash the entire blob on gun after generating a keypair, so you can re-create the same keypair and retrieve data stashed at a node with id set from public key, this can be a separate issue.

**Comment by jazzyjackson** [comment]
Relevant PR is #11

**Comment by amark** [comment]
* opt in feature (for any prying spying eyes looking at these issues), encrypted, etc. just updated the issue to reflect my anal security uptightness. We're not just gonna be (?the first?) open source payment processor, we're gonna tote'n set new security records & standards for all banks/processors! 🔥
