### ISSUE TITLE
Fraction new line support 

### ISSUE THREAD

**Issue by amark** [eraeco/pay#20]
Found out on 1 of my gun checks the fraction is super super long and overflows into a newline on the physical check.

So newline should be allowed on ours, saved & rendered on deposit as well. And width should also force it to overflow top of necessary.

**Comment by jazzyjackson** [comment]
presuming this is your expected behavior, tested to render on send and receive

![image](https://github.com/eraeco/pay/assets/7675670/6b42d6f2-5646-4928-8669-b2254c0f3b08)

**Comment by amark** [comment]
solved.
