### ISSUE TITLE
Copy Paste no style

### ISSUE THREAD

**Issue by amark** [eraeco/pay#24]
When I paste my address or whatever into a Checkard check, the browser tries to bring the HTML/style from the other site.

Newlines should be preserved, but nothing else just the text.

This should just be a CSS setting, right? Else just `.text(.text())` on a contenteditable paste event or something should do the trick.

**Comment by jazzyjackson** [comment]
Started via #26, see note, I went with option 'B' for now

**Comment by amark** [comment]
solved
