### ISSUE TITLE
Setup Paylink on the Upgrade button / Trial Mode

### ISSUE THREAD

**Issue by jazzyjackson** [eraeco/pay#30]
This is trivial, setting the href of the button to the desired paylink once you determine the parameters (cost, payee)

IIRC we wanted to 'start the trial' and enable proprietorship upon clicking remember me at the same time as storing the encrypted data, and then scroll to the marketing tray -- and then the 'upgrade' button, should probably have target="_blank" to open the paylink in a new tab right? Do we need to change anything in localstorage at that point?

Actually, what's the process once they follow the paylink -- we just have the recipient email as part of the paylink to and they hit send right?

**Comment by amark** [comment]
this just got deployed. Hopefully no bugs lol... we'll see, if there is, will open a new issue. YAY its out!
