### ISSUE TITLE
Enable Premium Features when "upgrade" is clicked

### ISSUE THREAD

**Issue by jazzyjackson** [eraeco/pay#8]
On the marketing page, the upgrade button is a paylink that directs the individual to fill out a check to checkard -- clicking this button also goes ahead and flips a flag in localStorage to indicate that premium features are enabled -- thus, when landing on the paylink destination, if the individual has ever used checkard before, their banking information will already have been stashed in localStorage and there will be minimal friction for submitting the check to checkard.

**Comment by jazzyjackson** [comment]
#11 merged the Proprietor key on localStorage and localStorage.began represents when 'rememberme' was first clicked, but I'll leave this open since the desired behavior is to trigger on the upgrade button... I think once we have the upgrade button pointing to a paylink and the marketing tray is visible it makes sense to worry about this issue again.

**Comment by amark** [comment]
While we're in hacky stage we should after 30 days disable remember me anyways to force them to pay for another 30 days? Until we have good auto renewal setup (which will prob be it's own checkbox at some point granting permission).

**Comment by amark** [comment]
also implemented and just deployed, however hopefully no bugs, we'll see and if so will re-open. YAY its out!
